// <auto-generated />
namespace NiceBytes.Veterinary.DAL.ClientsMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Registros : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Registros));
        
        string IMigrationMetadata.Id
        {
            get { return "201505180302253_Registros"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
