//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceBytes.Veterinary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetsModel
    {
        public PetsModel()
        {
            this.Registries = new HashSet<Registry>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public int ClientsModelId { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string Breed { get; set; }
        public string Colour { get; set; }
        public System.DateTime DateEntry { get; set; }
    
        public virtual ClientsModel ClientsModel { get; set; }
        public virtual ICollection<Registry> Registries { get; set; }
    }
}
