//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceBytes.Veterinary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registry
    {
        public int Id { get; set; }
        public int PetsModelId { get; set; }
    
        public virtual PetsModel PetsModel { get; set; }
    }
}
